os: linux
dist: trusty
language: java

before_cache:
  # Do not cache a few Gradle files/directories (see https://docs.travis-ci.com/user/languages/java/#Caching)
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

install:
  # Download and unzip the Android command line tools (if not already there thanks to the cache mechanism)
  # Latest version of this file available here: https://developer.android.com/studio/#command-tools
  - if test ! -e $HOME/android-cmdline-tools/cmdline-tools.zip ; then curl https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip > $HOME/android-cmdline-tools/cmdline-tools.zip ; fi
  - unzip -qq -n $HOME/android-cmdline-tools/cmdline-tools.zip -d $HOME/android-cmdline-tools

  # Install or update Android SDK components (will not do anything if already up to date thanks to the cache mechanism)
  - echo y | $HOME/android-cmdline-tools/tools/bin/sdkmanager --sdk_root=$HOME/android-sdk 'platform-tools' > /dev/null
  # Latest version of build-tools available here: https://developer.android.com/studio/releases/build-tools.html
  - echo y | $HOME/android-cmdline-tools/tools/bin/sdkmanager --sdk_root=$HOME/android-sdk 'build-tools;30.0.2' > /dev/null
  - echo y | $HOME/android-cmdline-tools/tools/bin/sdkmanager --sdk_root=$HOME/android-sdk 'platforms;android-30' > /dev/null
  
  # Install Gradle
  - if test ! -e $HOME/gradle-6.5-bin.zip ; then wget https://services.gradle.org/distributions/gradle-6.5-bin.zip > $HOME/gradle-6.5-bin.zip ; fi
  - unzip -qq -n ./gradle-6.5-bin.zip -d $HOME/.gradle/

  # Install flutter
  - if test ! -e $HOME/flutter_linux_1.26.0-1.0.pre-dev.tar.xz ; then wget https://storage.googleapis.com/flutter_infra/releases/dev/linux/flutter_linux_1.26.0-1.0.pre-dev.tar.xz > $HOME/flutter_linux_1.26.0-1.0.pre-dev.tar.xz ; fi
  - tar -xf flutter_linux_1.26.0-1.0.pre-dev.tar.xz -C $HOME/devtools/

jdk: oraclejdk8
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  # flutter bin config
  - export FLUTTER_BIN="$HOME/devtools/flutter/bin"

  # Add custom bins to the path
  - export PATH="$PATH:$FLUTTER_BIN"
script:
  - flutter flutter doctor --android-licenses
  - flutter doctor

cache:
  directories:
    - $HOME/.pub-cache
    - $GRADLE_HOME=$PWD/gradle-6.5

    # Android SDK
    - $HOME/android-cmdline-tools
    - $HOME/android-sdk

    # Gradle dependencies
    - $HOME/.gradle/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

    # FLutter
    - $HOME/devtools/

    # Android build cache (see http://tools.android.com/tech-docs/build-cache)
    - $HOME/.android/build-cache

env:
  - ANDROID_HOME=$HOME/android-sdk